name: Cypress Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y gnupg ca-certificates && \
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 33E614A32AA3A4A2 && \
            echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list && \
            sudo apt-get update && sudo apt-get install -y k6
      - name: Run k6 performance tests
        run: npm run k6:run

      - name: Run Postman API tests
        run: npm run postman:run