name: Cypress Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Run k6 performance tests
        run: npm run k6:run

      - name: Run Postman API tests
        run: npm run postman:run